// src/app/layout.tsx

import type { Metadata } from 'next';
import './styles/globals.css';
import { Header } from '@/features/shared/layout/Header';
import { Footer } from '@/features/shared/layout/Footer';

export const metadata: Metadata = {
  title: 'Pokedex App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='font-poppins'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
