// src/app/layout.tsx

import type { Metadata } from 'next';
import './styles/globals.css';
import { ReactNode, Suspense } from 'react';
import Image from 'next/image';
import { Title } from '@/features/shared/ui/Title';
import { Header } from '@/features/shared/layout/Header';
import { Footer } from '@/features/shared/layout/Footer';

export const metadata: Metadata = {
  title: 'findpoké',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/images/favicon.ico' />
      </head>
      <body className='font-poppins'>
        <Suspense
          fallback={
            <div className='min-h-screen flex flex-col justify-center items-center bg-gray-50'>
              <Image
                src='/images/shared/pokeball.svg'
                alt='Loading…'
                width={100}
                height={100}
                className='animate-spin'
              />
              <Title className='text-lg text-gray-700 mt-4'>Loading…</Title>
            </div>
          }
        >
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
